services:
  - type: web
    name: farmaciadey
    env: static
    buildCommand: cd farmacia-dey && npm install && npm run build -- --configuration production
    staticPublishPath: farmacia-dey/dist/farmacia-dey/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
